name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: [self-hosted, Windows]
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: linux-amd64
          - goos: linux
            goarch: arm64
            suffix: linux-arm64
          - goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - goos: darwin
            goarch: arm64
            suffix: darwin-arm64
          - goos: windows
            goarch: amd64
            suffix: windows-amd64.exe
          - goos: windows
            goarch: arm64
            suffix: windows-arm64.exe

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      shell: powershell
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        $output_name = "secret_manager-${{ matrix.suffix }}"
        $env:GOOS = "${{ matrix.goos }}"
        $env:GOARCH = "${{ matrix.goarch }}"
        $version = "${{ github.ref_name }}"
        $commit = "${{ github.sha }}".Substring(0, 7)
        $date = Get-Date -Format "yyyy-MM-dd"
        go build -o $output_name -ldflags="-s -w -X main.version=$version -X main.commit=$commit -X main.date=$date" .

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: secret_manager-${{ matrix.suffix }}
        path: secret_manager-${{ matrix.suffix }}

  release:
    needs: build
    runs-on: [self-hosted, Windows]
    steps:
    - uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./artifacts/**/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}